dist: trusty
language: node_js
cache: yarn
node_js:
- '10'
- '12'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.2
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install --frozen-lockfile
after_failure:
- yarn build -- --inspect
script:
- yarn lint
- yarn test:coverage
- yarn build
after_success: yarn codecov
