dist: trusty
language: node_js
cache: yarn
node_js:
- '12'
- '13'
install:
- yarn install --frozen-lockfile
after_failure:
- yarn build -- --inspect
script:
- yarn lint
- yarn test:coverage
- yarn build
after_success: yarn codecov
